name: conda-fedora
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - abseil-cpp=20220623.0=h8cdb687_6
  - absl-py=2.0.0=pyhd8ed1ab_0
  - aiohttp=3.8.5=py310h2372a71_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alembic=1.9.4=pyhd8ed1ab_0
  - anyio=4.0.0=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=21.1.0=py310h6acc77f_2
  - arrow=1.3.0=pyhd8ed1ab_0
  - arrow-cpp=11.0.0=ha770c72_5_cpu
  - asttokens=2.4.0=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - async-timeout=4.0.2=py310h06a4308_0
  - attrs=23.1.0=pyh71513ae_1
  - audioread=3.0.1=py310hff52083_0
  - aws-c-auth=0.6.24=h84a1944_5
  - aws-c-cal=0.5.20=hc60faf5_6
  - aws-c-common=0.8.11=h0b41bf4_0
  - aws-c-compression=0.2.16=h034cb4b_3
  - aws-c-event-stream=0.2.18=h75388cd_6
  - aws-c-http=0.7.4=hf084cc8_2
  - aws-c-io=0.13.17=h10df833_2
  - aws-c-mqtt=0.8.6=hc41645a_6
  - aws-c-s3=0.2.4=h1b8f470_3
  - aws-c-sdkutils=0.1.7=h034cb4b_3
  - aws-checksums=0.1.14=h034cb4b_3
  - aws-crt-cpp=0.19.7=h0073717_7
  - aws-sdk-cpp=1.10.57=h4707e7a_4
  - babel=2.12.1=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - bcrypt=4.1.2=py310hcb5633a_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - blas=1.0=mkl
  - bleach=6.0.0=pyhd8ed1ab_0
  - blinker=1.6.2=pyhd8ed1ab_0
  - brotli=1.0.9=h166bdaf_9
  - brotli-bin=1.0.9=h166bdaf_9
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2024.2.2=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.1=pyhd8ed1ab_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.15.1=py310h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - configargparse=1.7=pyhd8ed1ab_0
  - configparser=5.3.0=pyhd8ed1ab_0
  - contourpy=1.1.1=py310hd41b1e2_1
  - cryptography=41.0.3=py310hdda0065_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cycler=0.11.0=pyhd8ed1ab_0
  - databricks-cli=0.18.0=pyhd8ed1ab_0
  - debugpy=1.8.0=py310hc6cd4ac_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docker-py=6.1.3=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - easydict=1.9=py_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py310h06a4308_0
  - flask=3.0.0=pyhd8ed1ab_0
  - fonttools=4.42.1=py310h2372a71_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.4.0=py310h2372a71_1
  - gettext=0.21.1=h27087fc_0
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.1=h5eee18b_3
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.37=pyhd8ed1ab_0
  - glog=0.6.0=h6f12383_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - google-auth=2.23.2=pyhca7485f_0
  - google-auth-oauthlib=1.0.0=pyhd8ed1ab_1
  - grpc-cpp=1.51.1=h27aab58_1
  - grpcio=1.51.1=py310h4a5735c_1
  - gunicorn=21.2.0=py310hff52083_1
  - h3=4.1.0=hcb278e6_0
  - h3-py=3.7.6=py310hc6cd4ac_1
  - hdf5=1.14.3=nompi_h4f84152_100
  - idna=3.4=py310h06a4308_0
  - imageio=2.33.1=pyh8c1a49c_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.1.0=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - ipykernel=6.25.2=pyh2140261_0
  - ipympl=0.9.3=pyhd8ed1ab_0
  - ipython=8.16.1=pyh0d859eb_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jedi=0.19.0=pyhd8ed1ab_0
  - jinja2=3.1.2=py310h06a4308_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_1
  - json5=0.9.14=pyhd8ed1ab_0
  - jsonpointer=2.4=py310hff52083_3
  - jsonschema=4.19.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.7.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.19.1=pyhd8ed1ab_0
  - jupyter-lsp=2.2.0=pyhd8ed1ab_0
  - jupyter_client=8.3.1=pyhd8ed1ab_0
  - jupyter_core=5.3.2=py310hff52083_0
  - jupyter_events=0.7.0=pyhd8ed1ab_2
  - jupyter_server=2.7.3=pyhd8ed1ab_1
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab=4.0.6=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.25.0=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.9=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py310hd41b1e2_1
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h7b6447c_0
  - lazy_loader=0.3=pyhd8ed1ab_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libabseil=20220623.0=cxx17_h05df665_6
  - libaec=1.1.2=h59595ed_1
  - libarrow=11.0.0=h2ebd325_5_cpu
  - libbrotlicommon=1.0.9=h166bdaf_9
  - libbrotlidec=1.0.9=h166bdaf_9
  - libbrotlienc=1.0.9=h166bdaf_9
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.7.2.10=0
  - libcurand=10.3.3.141=0
  - libcurl=8.4.0=hca28451_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.10=h28343ad_4
  - libffi=3.4.4=h6a678d5_0
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.2.0=h807b86a_2
  - libgfortran-ng=13.2.0=h69a702a_2
  - libgfortran5=13.2.0=ha4646dd_2
  - libgoogle-cloud=2.7.0=h21dfe5b_1
  - libgrpc=1.51.1=h4fad500_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnghttp2=1.52.0=h61bc06f_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.21.12=hfc55251_2
  - librosa=0.10.1=pyhd8ed1ab_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.18.0=h5e4af38_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=14.0.6=h9e868ea_0
  - llvmlite=0.40.0=py310he621ea3_0
  - lmdb=0.9.31=hd590300_0
  - lz4-c=1.9.4=h6a678d5_0
  - mako=1.3.0=pyhd8ed1ab_0
  - markdown=3.4.4=pyhd8ed1ab_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - matplotlib-base=3.8.0=py310h62c0568_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=3.0.1=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46343
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - mlflow=2.9.2=py310ha13cd29_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpg123=1.32.2=h59595ed_0
  - mpmath=1.3.0=py310h06a4308_0
  - msgpack-python=1.0.6=py310hd41b1e2_0
  - multidict=6.0.4=py310h1fa729e_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - natsort=8.4.0=pyhd8ed1ab_0
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert-core=7.8.0=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py310h06a4308_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - numba=0.57.1=py310h0f6aa51_0
  - numpy=1.24.3=py310h5f9d8c6_1
  - numpy-base=1.24.3=py310hb5e798b_1
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.2.1=hd590300_0
  - orc=1.8.2=hfdbbad2_2
  - overrides=7.4.0=pyhd8ed1ab_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.1.1=py310hcc13569_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - paramiko=3.4.0=pyhd8ed1ab_0
  - parquet-cpp=1.5.1=2
  - parso=0.8.3=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - patsy=0.5.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py310h6a678d5_1
  - pip=23.2.1=py310h06a4308_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=3.10.0=py310h06a4308_0
  - plotly=5.17.0=pyhd8ed1ab_0
  - pooch=1.7.0=pyha770c72_3
  - prometheus_client=0.17.1=pyhd8ed1ab_0
  - prometheus_flask_exporter=0.23.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - protobuf=4.21.12=py310heca2aa9_0
  - psutil=5.9.5=py310h2372a71_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=11.0.0=py310h633f555_5_cpu
  - pyasn1=0.5.0=pyhd8ed1ab_0
  - pyasn1-modules=0.3.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_0
  - pynacl=1.5.0=py310h2372a71_3
  - pyopenssl=23.2.0=py310h06a4308_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py310h06a4308_0
  - pysoundfile=0.12.1=pyhd8ed1ab_0
  - python=3.10.13=h955ad1f_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.18.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-lmdb=1.4.1=py310hdf73078_1
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=2.0.1=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - pyyaml=6.0.1=py310h2372a71_1
  - pyzmq=25.1.1=py310h5bbb5d0_1
  - querystring_parser=1.2.4=py_0
  - re2=2023.02.01=hcb278e6_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=pyhd8ed1ab_0
  - requests=2.31.0=py310h06a4308_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.10.3=py310hcb5633a_1
  - rsa=4.9=pyhd8ed1ab_0
  - s2n=1.3.37=h3358134_0
  - scikit-learn=1.3.1=py310h1fdf081_0
  - seaborn=0.13.0=hd8ed1ab_0
  - seaborn-base=0.13.0=pyhd8ed1ab_0
  - send2trash=1.8.2=pyh41d4057_0
  - sentry-sdk=1.31.0=pyhd8ed1ab_0
  - setproctitle=1.3.2=py310h2372a71_2
  - setuptools=68.0.0=py310h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.10=h9fff704_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - soxr=0.1.3=h0b41bf4_3
  - soxr-python=0.3.5=py310h1f7b6fc_1
  - sqlalchemy=1.4.49=py310h2372a71_1
  - sqlite=3.41.2=h5eee18b_0
  - sqlparse=0.4.4=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.0=py310h1f7b6fc_2
  - sympy=1.11.1=py310h06a4308_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=8.2.3=pyhd8ed1ab_0
  - tensorboard=2.14.1=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py310h75e40e8_1
  - terminado=0.17.1=pyh41d4057_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - torchaudio=2.0.2=py310_cu118
  - torchinfo=1.8.0=pyhd8ed1ab_0
  - torchtriton=2.0.0=py310
  - torchvision=0.15.2=py310_cu118
  - tornado=6.3.3=py310h2372a71_1
  - tqdm=4.65.0=py310h2f386ee_0
  - traitlets=5.10.1=pyhd8ed1ab_0
  - types-python-dateutil=2.8.19.14=pyhd8ed1ab_0
  - typing_extensions=4.7.1=py310h06a4308_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2023c=h04d1e81_0
  - unicodedata2=15.1.0=py310h2372a71_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=1.26.16=py310h06a4308_0
  - wandb=0.15.11=pyhd8ed1ab_0
  - wcwidth=0.2.8=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.6.3=pyhd8ed1ab_0
  - werkzeug=3.0.0=pyhd8ed1ab_0
  - wheel=0.38.4=py310h06a4308_0
  - widgetsnbextension=4.0.9=pyhd8ed1ab_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.2=py310h2372a71_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hc292b87_0
  - pip:
      - acoustics==0.2.6
      - addict==2.4.0
      - ansi2html==1.8.0
      - cftime==1.6.2
      - dash==2.14.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - datetime==5.2
      - gevent==23.9.1
      - greenlet==3.0.1
      - gwebsocket==0.9.9
      - h5py==3.10.0
      - hexagdly==2.0.2
      - iniconfig==2.0.0
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - lightning-utilities==0.10.1
      - nbformat==5.7.0
      - netcdf4==1.6.4
      - notebook==7.0.6
      - open3d==0.17.0
      - pluggy==1.3.0
      - positional-encodings==6.0.3
      - pyquaternion==0.9.9
      - pytest==7.4.3
      - python-sofa==0.2.0
      - pyvista==0.43.1
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - resampy==0.4.2
      - retrying==1.3.4
      - scipy==1.11.3
      - scooby==0.9.2
      - sounddevice==0.4.6
      - spaudiopy==0.1.5
      - torch-tb-profiler==0.4.3
      - torchmetrics==1.3.0.post0
      - utc==0.0.3
      - vtk==9.3.0
      - zope-event==5.0
      - zope-interface==6.0
prefix: /home/ricfalcon/anaconda3/envs/conda-fedora

